module.exports = {
  content: ["./app/**/*.{html,js}"],
  theme: {
    colors: {
      "background-light": "#ffffff",
      "background-dark": "#384155",
      "gutter-light": "#ffedd5",
      "gutter-dark": "#94a3b8",
      "border-dark": "#edf5ff",
      "card-background": "#475569",
      "card-highlight": "#0369a1",
      "text-primary-light": "#000000",
      "text-primary-dark": "#ffffff",
      "text-secondary-light": "#3d3d3d",
      "text-secondary-dark": "#c9c9c9",
      accent: "#fbbe24",
      "link-light": "#1d4fd8",
      "link-dark": "#93c4fd",
      "card-button": "#7e8c9c",
      warning: "#ff000066",
    },
    extend: {},
  },
  plugins: [],
};
